### PR TITLE
Vipin_Customer_Churn_Analysis_IDA

### PR DESCRIPTION
**Pull request by vipinsingh1221**
Hey Rehan,

Please review my code.

### CODE REVIEW

**Comment by rehanguha** [comment]
Some of the charts are not right like remove Pie charts and replace with Bar Plots, 1 chart is missing, and %inf string should have value at the last chart.

please update the above so that I can approve the PR
(Just change your code and commit, no need to raise a new PR again)

**Comment by rehanguha** [comment]
@vipinsingh1221 :: I have not seen any of the above mentioned point updated in the notebook. 

@Akash20x @prathmesh-jagtap @vikassingh3201 Please him him out as a team to solve some of the issues and add necessary details. Before coming to me please perform a peer review and update me so that I can do the final check.

**Comment by rehanguha** [comment]
@vipinsingh1221 Why did you merge the PR?

cc: @rutuja027

**Comment by rehanguha** [comment]
I have reverted the changes. Please correct the IDA errors.
For EDA correct the following:
LinAlgError: singular matrix
Add a TOC
Multivariate Analysis does not make sense
Add inference to all the viz

**Comment by vipinsingh1221** [comment]
Sure Rehan, I will do it today

**Pull request merged**
